Repository GPlates/gplately, pull requests merged in 2024-06, with the labels that each got.

#186 Ensure `_load_FeatureCollection` correctly assigns `filenames` attribute
  gplately/gpml.py
  tests-dir/pytestcases/test_1_reconstructions.py
Labels: bug

#209 Use multipoint coverage to save age gridding debug data #208
  gplately/oceans.py
  gplately/pygplates.py
  tests-dir/unittest/test_age_grid.py
Labels: enhancement, low

#204 199 sort out various issues in online doc
  .github/workflows/deploy_documentation.yaml
  README.md
  gplately/__init__.py
  gplately/__main__.py
  gplately/commands/__init__.py
  gplately/commands/create_age_grids.py
  gplately/commands/feature_filter.py
  gplately/data.py
  gplately/decorators.py
  gplately/download.py
  gplately/exceptions.py
  gplately/geometry.py
  gplately/gpml.py
  gplately/grids.py
  gplately/oceans.py
  gplately/parallel.py
  gplately/plot.py
  gplately/ptt/__init__.py
  gplately/ptt/cleanup_topologies.py
  gplately/ptt/continent_contours.py
  gplately/ptt/convert_xy_to_gplates.py
  gplately/ptt/diagnose_rotations.py
  gplately/ptt/documentation.py
  gplately/ptt/fix_crossovers.py
  gplately/ptt/gpmdb.py
  gplately/ptt/remove_plate_rotations.py
  gplately/ptt/resolve_topologies.py
  gplately/ptt/ridge_spreading_rate.py
  gplately/ptt/rotation_tools.py
  gplately/ptt/separate_ridge_transform_segments.py
  gplately/ptt/subduction_convergence.py
  gplately/ptt/utils/GPMLTools.py
  gplately/ptt/utils/__init__.py
  gplately/ptt/utils/call_system_command.py
  gplately/ptt/utils/points_in_polygons.py
  gplately/ptt/utils/points_spatial_tree.py
  gplately/ptt/utils/proximity_query.py
  gplately/ptt/utils/reconstruct_by_topologies.py
  gplately/ptt/utils/subduction_teeth.py
  gplately/ptt/velocity_tools.py
  gplately/pygplates.py
  gplately/reconstruction.py
  gplately/tools.py
  gplately/utils/__init__.py
  gplately/utils/feature_utils.py
  gplately/utils/io_utils.py
  gplately/utils/log_utils.py
  gplately/utils/plot_utils.py
  gplately/utils/seafloor_grid_utils.py
Labels: enhancement
